# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParteObra
                                 A QGIS plugin
 Parte de Obra con Fotos de Campo Comentadas incluso Incidencias
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-18
        copyright            : (C) 2023 by Antonio Carlos Benavides García
        email                : antonio.benavides@usal.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ParteObra class from file ParteObra.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ParteObra import ParteObra
    return ParteObra(iface)
